### ISSUE TITLE
where is the architectural code for Samba

### ISSUE THREAD

**Issue by sunxin010203** [microsoft/Samba#13]
Thank you for your wonderful work, and I would like to ask where is the architectural code for Samba?

**Comment by renll** [comment]
The config for Samba 421M is [here](https://github.com/microsoft/Samba/blob/6b7935bc7c2e25588a0cbc7bf21b536f13edf0b1/lit_gpt/config.py#L382), which controls the flags in the [modeling file](https://github.com/microsoft/Samba/blob/main/lit_gpt/model.py) to behave as the Samba architecture.
