### ISSUE TITLE
Too late for a name change?

### ISSUE THREAD

**Issue by StraightfaceStudios** [microsoft/Samba#14]
This is seriously confusing with Microsoft SMB/Samba. 

`Samba is the standard Windows interoperability suite of programs for Linux and Unix. Samba is Free Software licensed under the GNU General Public License and the Samba project is a member of the Software Freedom Conservancy. Since 1992, Samba has provided secure, stable and fast file and print services for all clients using the SMB/CIFS protocol, such as all versions of DOS and Windows, OS/2, Linux and many others. Samba is an important component to seamlessly integrate Linux/Unix Servers and Desktops into Active Directory environments. It can function both as a domain controller or as a regular domain member.`

https://github.com/samba-team/samba

**Comment by renll** [comment]
Yep, only until going through the final internal review for repo publication, we realized that there was an MSFT software called Samba. It is just too late for us at that time to change the name...
