### ISSUE TITLE
Vocab size mismatch between config.py and the paper

### ISSUE THREAD

**Issue by jgcb00** [microsoft/Samba#18]
Hi,
Thanks for this very interesting paper ! 
Comparing the table 9 in the paper and the `config.py` file, it looks like there is a mismatch between the vocabulary size.
Which one did you actually used ?

Best Regards,

**Comment by renll** [comment]
Hi, Table 9 is for models at the scale of Samba 1.7B which is not released in this repo. This repo only contains the training codebase for Samba 421M and Samba 1.3B.

**Comment by jgcb00** [comment]
My bad, thanks !
