### ISSUE TITLE
inference code 

### ISSUE THREAD

**Issue by myounghanmain** [microsoft/Samba#19]
I'm turning the learning. Is there any code to infer the model after learning? If not, when are you going to upload the inference code? And is there any reference or url to refer to for inference?

**Comment by richardburleigh** [comment]
I made a hacky inference script a while ago. See here [richardburleigh/Samba](https://github.com/richardburleigh/Samba/blob/main/inference.py).

**Comment by myounghanmain** [comment]
oh Thank you so much. I'll try it out
