### ISSUE TITLE
Sliding Window Attention RoPE

### ISSUE THREAD

**Issue by LeoXinhaoLee** [microsoft/Samba#25]
Hi, thank you so much for releasing code for this cool work!

In the paper, it is mentioned that "The RoPE relative positions are applied within the sliding window". Does this mean in each sliding window of size 2048, RoPE embedding cache of length 2048 is applied? This seems complicated to implement since the same key in different sliding windows has different position.

However, I noticed that in [code](https://github.com/microsoft/Samba/blob/6b7935bc7c2e25588a0cbc7bf21b536f13edf0b1/lit_gpt/model.py#L198), during training, RoPE cache of sequence length (`self.config.block_size`) is directly applied on the entire Q and K. If this is the case, I'm wondering how I should add RoPE for extrapolation beyond training sequence length?

Thank you very much for your time and help!

**Comment by renll** [comment]
Hi, thanks for your interest in our work!

Actually, it is just normal RoPE applied on the entire Q, K. Since RoPE is relative, it is equivalent to apply rope inside the sliding window.

[This line](https://github.com/microsoft/Samba/blob/6b7935bc7c2e25588a0cbc7bf21b536f13edf0b1/lit_gpt/model.py#L199) shows how rope is handled when the sequence length is longer than training.

**Comment by LeoXinhaoLee** [comment]
Thank you for your reply! 

It's totally understandable from the perspective of efficiency to apply RoPE on the entire QK.

However, my original thinking was each window will use RoPE of length = window size, and reset RoPE for the next window, such that the length of RoPE on depends on window size rather than sequence length. This should not be equivalent to applying RoPE of length = sequence length to the entire QK, and may produce better extrapolation ability, as there's no dependency on a pre-specified context length.

I'm wondering if my understanding is correct and if there's any study about this? Thank you very much!

**Comment by LeoXinhaoLee** [comment]
I see. Thank you very much!
