### ISSUE TITLE
LitGPT

### ISSUE THREAD

**Issue by rasbt** [microsoft/Samba#6]
Congrats on this research milestone 🙌! And it’s nice to see that our [LitGPT](https://github.com/Lightning-AI/litgpt) library has been has been useful for this project. However, note that LitGPT is an open-source project, and the Apache 2.0 open-source [license]([https://github.com/Lightning-AI/litgpt/blob/main/LICENSE) requires including the original license and copyright notice. Right now, the files in Samba’s [lit_gpt](https://github.com/microsoft/Samba/tree/c16f041d2f0d9087e7e38e7b9fb4ae68ccecf72d/lit_gpt) subfolder only say 

```
# Copyright (c) Microsoft Corporation ...
``` 

which needs to be updated to also include 
```
Copyright Lightning AI. Licensed under the Apache License 2.0,
see LICENSE file at https://github.com/Lightning-AI/litgpt/blob/main/LICENSE
```
Could you please correct this mistake as soon as possible and include the correct LitGPT license reference.

**Comment by renll** [comment]
Just fixed it! LitGPT is a great library for correctly and stably pretraining LLMs. Thanks for the invaluable contribution of Lightning AI to the community of open-source LLMs!

**Comment by rasbt** [comment]
Glad to hear, and thanks for quickly resolving this!
