### ISSUE TITLE
Inferrence Code

### ISSUE THREAD

**Issue by richardburleigh** [microsoft/Samba#8]
Amazing work, team! Thank you sincerely for sharing.

I have trained a toy model but have completely failed creating an inference script. Sharing one would be sincerely appreciated!

**Comment by nampdn** [comment]
Are you able to do inference now?

**Comment by renll** [comment]
Thanks for the interests. We added evaluation [here](https://github.com/microsoft/Samba?tab=readme-ov-file#evaluation).
